name: Simple Echo

on:
  push:
    branches:
      - main   # run when code is pushed to main branch
  workflow_dispatch:   # allows manual trigger

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo message
        run: echo "Hello World from GitHub Actions"
